export const recentJobs = [
    {
      id: '1',
      title: 'Product Designer',
      company: 'Google Inc',
      location: 'California, USA',
      tags: ['Senior Designer', 'Full Time'],
      salary: '$15K',
      logo: require('../assets/icons/google.png'), 
      postedTime: '1 day ago',
      salary1: '$120k - $150k',
      jobType: 'Full-Time',
      position: 'Senior Designer',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas architecto mollitia dolore incidunt tempora ad laborum beatae tempore dignissimos ut? Molestias, architecto ullam consectetur maxime earum expedita id accusantium eum!',
      requirements: [
        'Experience with Figma and Sketch.',
        'Proficiency in user-centered design.',
        'Strong communication skills.',
      ],
      locationDetails: 'Overlook Avenue, Belvidere, NJ, USA',
      mapImage: require('../assets/icons/Map.png'),
      informations: {
        Qualification: "Bachelor's Degree",
        Experience: '5+ Years',
        Specialization: 'Design',
      },
      facilities: [
        'Medical',
        'Dental',
        'Technical Certifications',
        'Meal Allowance',
        'Transport Allowance',
        'Regular Hours',
        'Monday-Friday',
      ],
      about: [
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas.",
        "Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain.",
      ],
      website: "https://www.google.com",
      industry: "Internet product",
      employeeSize: "132,121 Employees",
      headOffice: "Mountain View, California, Amerika Serikat",
      type: "Multinational company",
      since: "1998",
      specialization: "Search technology, Web computing, Software and Online advertising",
      gallery: [
        require('../assets/icons/team.png'),
        require('../assets/icons/team.png')
      ],
    },
    {
      id: '2',
      title: 'Software Engineer',
      company: 'Facebook',
      location: 'Menlo Park, USA',
      tags: ['Mid-level', 'Full Time'],
      salary: '$12K',
      logo: require('../assets/icons/facebook.png'), 
      postedTime: '1 day ago',
      salary1: '$120k - $150k',
      jobType: 'Full-Time',
      position: 'Senior Designer',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas architecto mollitia dolore incidunt tempora ad laborum beatae tempore dignissimos ut? Molestias, architecto ullam consectetur maxime earum expedita id accusantium eum!',
      requirements: [
        'Experience with Figma and Sketch.',
        'Proficiency in user-centered design.',
        'Strong communication skills.',
      ],
      locationDetails: 'Overlook Avenue, Belvidere, NJ, USA',
      mapImage: require('../assets/icons/Map.png'),
      informations: {
        Qualification: "Bachelor's Degree",
        Experience: '5+ Years',
        Specialization: 'Design',
      },
      facilities: [
        'Medical',
        'Dental',
        'Technical Certifications',
        'Meal Allowance',
        'Transport Allowance',
        'Regular Hours',
        'Monday-Friday',
      ],
      about: [
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas.",
        "Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain.",
      ],
      website: "https://www.facebook.com",
      industry: "Internet product",
      employeeSize: "132,121 Employees",
      headOffice: "Mountain View, California, Amerika Serikat",
      type: "Multinational company",
      since: "1998",
      specialization: "Search technology, Web computing, Software and Online advertising",
      gallery: [
        require('../assets/icons/team.png'),
        require('../assets/icons/team.png')
      ],
    },
    {
      id: '3',
      title: 'UX Researcher',
      company: 'Amazon',
      location: 'Seattle, USA',
      tags: ['Junior', 'Part Time'],
      salary: '$10K',
      logo: require('../assets/icons/Amazon.png'), 
      postedTime: '1 day ago',
      salary1: '$120k - $150k',
      jobType: 'Full-Time',
      position: 'Senior Designer',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas architecto mollitia dolore incidunt tempora ad laborum beatae tempore dignissimos ut? Molestias, architecto ullam consectetur maxime earum expedita id accusantium eum!',
      requirements: [
        'Experience with Figma and Sketch.',
        'Proficiency in user-centered design.',
        'Strong communication skills.',
      ],
      locationDetails: 'Overlook Avenue, Belvidere, NJ, USA',
      mapImage: require('../assets/icons/Map.png'),
      informations: {
        Qualification: "Bachelor's Degree",
        Experience: '5+ Years',
        Specialization: 'Design',
      },
      facilities: [
        'Medical',
        'Dental',
        'Technical Certifications',
        'Meal Allowance',
        'Transport Allowance',
        'Regular Hours',
        'Monday-Friday',
      ],
      about: [
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas.",
        "Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain.",
      ],
      website: "https://www.Amazon.com",
      industry: "Internet product",
      employeeSize: "132,121 Employees",
      headOffice: "Mountain View, California, Amerika Serikat",
      type: "Multinational company",
      since: "1998",
      specialization: "Search technology, Web computing, Software and Online advertising",
      gallery: [
        require('../assets/icons/team.png'),
        require('../assets/icons/team.png')
      ],
    },
  ];