const translations = {
   en: {
     hello: 'Hello',
     attr1: 'Specialization',
     attr2: 'View all',
     attr3: 'Job Recommendation',
     notification: 'Notification',
     darkmode: 'Dark Mode',
     language: 'Language',
     password: 'Password',
     logout: 'Logout',
     setting: 'Setting',
     logoutConfirmation: 'Are you sure you want to log out?',
     yes: 'Yes',
     no: 'No',
     changePassword: 'Change Password',
     currentPassword: 'Current Password',
     newPassword: 'New Password',
     confirmPassword: 'Confirm Password',
     submit: 'Submit',
     findYourJob: 'Find Your Job',
     recentJobList: 'Recent Job List'
   },
   hi: {
     hello: 'नमस्ते',
     attr1: 'विशेषज्ञता',
     attr2: 'सभी देखें',
     attr3: 'नौकरी सिफारिश',
     notification: 'सूचना',
     darkmode: 'डार्क मोड',
     language: 'भाषा',
     password: 'पासवर्ड',
     logout: 'लॉग आउट',
     setting: 'सेटिंग्स',
     logoutConfirmation: 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
     yes: 'हाँ',
     no: 'नहीं',
     changePassword: 'पासवर्ड बदलें',
     currentPassword: 'वर्तमान पासवर्ड',
     newPassword: 'नया पासवर्ड',
     confirmPassword: 'पासवर्ड की पुष्टि करें',
     submit: 'सबमिट करें',
     findYourJob: 'अपनी नौकरी खोजें',
     recentJobList: 'हाल की नौकरी सूची'
   },
   or: {
     hello: 'ନମସ୍କାର',
     attr1: 'ବିଶେଷଜ୍ଞତା',
     attr2: 'ସମ୍ପୂର୍ଣ୍ଣ ଦେଖନ୍ତୁ',
     attr3: 'ଚାକିରି ସୁପାରିଶ',
     notification: 'ସୂଚନା',
     darkmode: 'ଡାର୍କ ମୋଡ୍',
     language: 'ଭାଷା',
     password: 'ପାସୱାର୍ଡ୍',
     logout: 'ଲଗଅଉଟ୍',
     setting: 'ସେଟିଂସ୍',
     logoutConfirmation: 'ଆପଣ କି ସତରେ ଲଗଅଉଟ୍ କରିବାକୁ ଚାହାନ୍ତି?',
     yes: 'ହଁ',
     no: 'ନାହିଁ',
     changePassword: 'ପାସୱାର୍ଡ୍ ବଦଳାନ୍ତୁ',
     currentPassword: 'ବର୍ତ୍ତମାନ ପାସୱାର୍ଡ୍',
     newPassword: 'ନୂତନ ପାସୱାର୍ଡ୍',
     confirmPassword: 'ପାସୱାର୍ଡ୍ ନିଶ୍ଚିତ କରନ୍ତୁ',
     submit: 'ସବମିଟ୍ କରନ୍ତୁ',
     findYourJob: 'ଆପଣଙ୍କ ଚାକିରି ଖୋଜନ୍ତୁ',
     recentJobList: 'ସମ୍ପ୍ରତି ଚାକିରି ତାଲିକା'
   }
 };
 
 export default translations;
 