const translations = {
  en: {
    editprofile: 'Edit Profile',
    phone: 'Phone',
    description: 'Description',
    address: 'Address',
    website: 'Website',
    socialmedia: 'Social Media Link',
    industry: 'Industry',
    since: 'Since',
    specialization: 'Specialization',
    cancel: 'Cancel',
    savechanges: 'Save Changes',
    dateofbirth: 'Date of Birth',
    about: 'About',
    skill: 'Skill',
    experience: 'Experience',
    university: 'University',
    education: 'Education',
  },
  hi: {
    editprofile: 'प्रोफ़ाइल संपादित करें',
    phone: 'फ़ोन',
    description: 'विवरण',
    address: 'पता',
    website: 'वेबसाइट',
    socialmedia: 'सोशल मीडिया लिंक',
    industry: 'उद्योग',
    since: 'से',
    specialization: 'विशेषज्ञता',
    cancel: 'रद्द करें',
    savechanges: 'परिवर्तनों को सहेजें',
    dateofbirth: 'जन्म तिथि',
    about: 'के बारे में',
    skill: 'कौशल',
    experience: 'अनुभव',
    university: 'विश्वविद्यालय',
    education: 'शिक्षा',
  },
  or: {
    editprofile: 'ପ୍ରୋଫାଇଲ ସମ୍ପାଦନା କରନ୍ତୁ',
    phone: 'ଫୋନ୍',
    description: 'ବିବରଣୀ',
    address: 'ଠିକଣା',
    website: 'ୱେବସାଇଟ୍',
    socialmedia: 'ସୋସିଆଲ ମିଡିଆ ଲିଙ୍କ',
    industry: 'ଉଦ୍ୟୋଗ',
    since: 'ଥିଲେ',
    specialization: 'ବିଶେଷଜ୍ଞତା',
    cancel: 'ବିଚ୍ଛେଦ କରନ୍ତୁ',
    savechanges: 'ପରିବର୍ତ୍ତନ ସଂରକ୍ଷିତ କରନ୍ତୁ',
    dateofbirth: 'ଜନ୍ମ ତାରିଖ',
    about: 'ବିଷୟରେ',
    skill: 'ଦକ୍ଷତା',
    experience: 'ଅଭିଜ୍ଞତା',
    university: 'ବିଶ୍ୱବିଦ୍ୟାଳୟ',
    education: 'ଶିକ୍ଷା',
  },
};

export default translations;
